/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectooperativos1gonzalezmicale;

import java.io.*;
import java.util.concurrent.Semaphore;

/**
 *
 * @author Carlos Gonzalez CI: 26.996.222, 
 * Ricardo Micale CI: 27.111.658
 */
public class Interfaz extends javax.swing.JFrame {
    //tiempo de un dia
    int tiempo;
    //dias entre despacho
    int dias;
    //contadores de la cantidad de partes
    public static volatile int contBotones = 0;
    public static volatile int contBrazos = 0;
    public static volatile int contPiernas = 0;
    public static volatile int contCuerpos = 0;
    //contadores de panas disponibles y panas totales
    int contPanas = 0;
    int contPanasTotales = 0;
    //cantidades iniciales de productores
    int inicioProdBtn = 0;
    int inicioProdBrazos = 0;
    int inicioProdPiernas = 0;
    int inicioProdCuerpos = 0;
    int inicioEnsambladores = 0;
    //cantidad maxima de partes, productores y ensambladores
    //partes
    int maxBtn = 0;
    int maxBrazos = 0;
    int maxPiernas = 0;
    int maxCuerpos = 0;
    //productores
    int maxProdBtn;
    int maxProdBrazos;
    int maxProdPiernas;
    int maxProdCuerpos;
    //ensamblador
    int maxEnsambladores;
    //semaforos para los productores
    Semaphore mutexBtn = new Semaphore(1);
    Semaphore mutexBrazos = new Semaphore(1);
    Semaphore mutexPiernas = new Semaphore(1);
    Semaphore mutexCuerpos = new Semaphore(1);
    Semaphore mutexEns = new Semaphore(1);
    
    Semaphore semProdBtn;
    Semaphore semProdBrazos;
    Semaphore semProdPiernas;
    Semaphore semProdCuerpos;
    //semaforo del ensamblador
    Semaphore semProdEns = new Semaphore(99999);
    
    //Estos valores van asi aqui???
    Semaphore semEnsaBtn = new Semaphore(8);
    Semaphore semEnsaBrazos = new Semaphore(2);
    Semaphore semEnsaPiernas = new Semaphore(2);
    Semaphore semEnsaCuerpos = new Semaphore(1);
    //semaforo del ensamblador
    Semaphore semEnsaEns = new Semaphore(0);
    //nombre de los productores y ensambladores
    String btnProdName = "boton 1";
    String brazProdName = "brazos 1";
    String pierProdName = "piernas 1";
    String cuerpoProdName = "cuerpos 1";
    String ensamName = "ensamblador 1";
    //cantidad productores de cada parte
    Productor[] productoresBtn;
    Productor[] productoresBrazos;
    Productor[] productoresPiernas;
    Productor[] productoresCuerpos;
    //cantidad ensambladores
    Ensamblador[] ensambladores;
    
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Estatus de produccion");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelProd1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lableBtnProd1 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        labelBrazosProd1 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        labelPiernasProd1 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        labelCuerpoProd1 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelProd = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lableBtnProd = new javax.swing.JLabel();
        delBotones = new javax.swing.JButton();
        aggBotones = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        labelBrazosProd = new javax.swing.JLabel();
        delBrazos = new javax.swing.JButton();
        aggBrazos = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        labelPiernasProd = new javax.swing.JLabel();
        aggPiernas = new javax.swing.JButton();
        delPiernas = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        labelCuerpoProd = new javax.swing.JLabel();
        aggCuerpo = new javax.swing.JButton();
        delCuerpo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        diasRestLabel = new javax.swing.JLabel();
        jefeLabel = new javax.swing.JLabel();
        gerenteLabel = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        ctdBtns = new javax.swing.JLabel();
        ctdBrazos = new javax.swing.JLabel();
        ctdPiernas = new javax.swing.JLabel();
        ctdCuerpos = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        labelCtdEnsam = new javax.swing.JLabel();
        aggEnsamblador = new javax.swing.JButton();
        delEnsamblador = new javax.swing.JButton();
        labelCtdEnsam1 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        panasDisponLabel = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        panasTotalesLabel = new javax.swing.JLabel();
        labelCtdEnsam2 = new javax.swing.JLabel();

        panelProd1.setBackground(new java.awt.Color(255, 255, 255));
        panelProd1.setPreferredSize(new java.awt.Dimension(330, 160));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(0, 35));

        lableBtnProd1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lableBtnProd1.setForeground(new java.awt.Color(51, 51, 51));
        lableBtnProd1.setText("Botones:");

        jButton9.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jButton9.setForeground(new java.awt.Color(51, 51, 51));
        jButton9.setText("-");
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton10.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jButton10.setForeground(new java.awt.Color(51, 51, 51));
        jButton10.setText("+");
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lableBtnProd1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(jButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9)
                .addGap(20, 20, 20))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lableBtnProd1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setPreferredSize(new java.awt.Dimension(0, 35));

        labelBrazosProd1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        labelBrazosProd1.setForeground(new java.awt.Color(51, 51, 51));
        labelBrazosProd1.setText("Brazos:");

        jButton11.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jButton11.setForeground(new java.awt.Color(51, 51, 51));
        jButton11.setText("-");
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton12.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jButton12.setForeground(new java.awt.Color(51, 51, 51));
        jButton12.setText("+");
        jButton12.setBorderPainted(false);
        jButton12.setContentAreaFilled(false);
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelBrazosProd1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton11)
                .addGap(18, 18, 18))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelBrazosProd1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setPreferredSize(new java.awt.Dimension(0, 35));

        labelPiernasProd1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        labelPiernasProd1.setForeground(new java.awt.Color(51, 51, 51));
        labelPiernasProd1.setText("Piernas:");

        jButton13.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jButton13.setForeground(new java.awt.Color(51, 51, 51));
        jButton13.setText("+");
        jButton13.setBorderPainted(false);
        jButton13.setContentAreaFilled(false);
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jButton14.setForeground(new java.awt.Color(51, 51, 51));
        jButton14.setText("-");
        jButton14.setBorderPainted(false);
        jButton14.setContentAreaFilled(false);
        jButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPiernasProd1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton14)
                .addGap(17, 17, 17))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(labelPiernasProd1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setPreferredSize(new java.awt.Dimension(0, 35));

        labelCuerpoProd1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        labelCuerpoProd1.setForeground(new java.awt.Color(51, 51, 51));
        labelCuerpoProd1.setText("Cuerpo:");

        jButton15.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jButton15.setForeground(new java.awt.Color(51, 51, 51));
        jButton15.setText("+");
        jButton15.setBorderPainted(false);
        jButton15.setContentAreaFilled(false);
        jButton15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jButton16.setForeground(new java.awt.Color(51, 51, 51));
        jButton16.setText("-");
        jButton16.setBorderPainted(false);
        jButton16.setContentAreaFilled(false);
        jButton16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCuerpoProd1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton16)
                .addGap(19, 19, 19))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(labelCuerpoProd1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout panelProd1Layout = new javax.swing.GroupLayout(panelProd1);
        panelProd1.setLayout(panelProd1Layout);
        panelProd1Layout.setHorizontalGroup(
            panelProd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );
        panelProd1Layout.setVerticalGroup(
            panelProd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProd1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 158, 182));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setPreferredSize(new java.awt.Dimension(120, 50));

        btnSalir.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(51, 51, 51));
        btnSalir.setText("SALIR");
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Estatus de produccion: Pana");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Productores");

        panelProd.setBackground(new java.awt.Color(255, 255, 255));
        panelProd.setPreferredSize(new java.awt.Dimension(330, 160));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(0, 35));

        lableBtnProd.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lableBtnProd.setForeground(new java.awt.Color(51, 51, 51));
        lableBtnProd.setText("Botones:");

        delBotones.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        delBotones.setForeground(new java.awt.Color(51, 51, 51));
        delBotones.setText("-");
        delBotones.setBorderPainted(false);
        delBotones.setContentAreaFilled(false);
        delBotones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delBotones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBotonesActionPerformed(evt);
            }
        });

        aggBotones.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        aggBotones.setForeground(new java.awt.Color(51, 51, 51));
        aggBotones.setText("+");
        aggBotones.setBorderPainted(false);
        aggBotones.setContentAreaFilled(false);
        aggBotones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aggBotones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aggBotonesMouseClicked(evt);
            }
        });
        aggBotones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggBotonesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lableBtnProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aggBotones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delBotones)
                .addGap(20, 20, 20))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lableBtnProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(delBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(aggBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(0, 35));

        labelBrazosProd.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        labelBrazosProd.setForeground(new java.awt.Color(51, 51, 51));
        labelBrazosProd.setText("Brazos:");

        delBrazos.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        delBrazos.setForeground(new java.awt.Color(51, 51, 51));
        delBrazos.setText("-");
        delBrazos.setBorderPainted(false);
        delBrazos.setContentAreaFilled(false);
        delBrazos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delBrazos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBrazosActionPerformed(evt);
            }
        });

        aggBrazos.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        aggBrazos.setForeground(new java.awt.Color(51, 51, 51));
        aggBrazos.setText("+");
        aggBrazos.setBorderPainted(false);
        aggBrazos.setContentAreaFilled(false);
        aggBrazos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aggBrazos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggBrazosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelBrazosProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aggBrazos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delBrazos)
                .addGap(18, 18, 18))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelBrazosProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delBrazos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aggBrazos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(0, 35));

        labelPiernasProd.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        labelPiernasProd.setForeground(new java.awt.Color(51, 51, 51));
        labelPiernasProd.setText("Piernas:");

        aggPiernas.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        aggPiernas.setForeground(new java.awt.Color(51, 51, 51));
        aggPiernas.setText("+");
        aggPiernas.setBorderPainted(false);
        aggPiernas.setContentAreaFilled(false);
        aggPiernas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aggPiernas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggPiernasActionPerformed(evt);
            }
        });

        delPiernas.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        delPiernas.setForeground(new java.awt.Color(51, 51, 51));
        delPiernas.setText("-");
        delPiernas.setBorderPainted(false);
        delPiernas.setContentAreaFilled(false);
        delPiernas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delPiernas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delPiernasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPiernasProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aggPiernas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delPiernas)
                .addGap(17, 17, 17))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(labelPiernasProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aggPiernas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(delPiernas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(0, 35));

        labelCuerpoProd.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        labelCuerpoProd.setForeground(new java.awt.Color(51, 51, 51));
        labelCuerpoProd.setText("Cuerpo:");

        aggCuerpo.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        aggCuerpo.setForeground(new java.awt.Color(51, 51, 51));
        aggCuerpo.setText("+");
        aggCuerpo.setBorderPainted(false);
        aggCuerpo.setContentAreaFilled(false);
        aggCuerpo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aggCuerpo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggCuerpoActionPerformed(evt);
            }
        });

        delCuerpo.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        delCuerpo.setForeground(new java.awt.Color(51, 51, 51));
        delCuerpo.setText("-");
        delCuerpo.setBorderPainted(false);
        delCuerpo.setContentAreaFilled(false);
        delCuerpo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delCuerpo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delCuerpoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCuerpoProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aggCuerpo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delCuerpo)
                .addGap(19, 19, 19))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(aggCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(delCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelCuerpoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelProdLayout = new javax.swing.GroupLayout(panelProd);
        panelProd.setLayout(panelProdLayout);
        panelProdLayout.setHorizontalGroup(
            panelProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
        );
        panelProdLayout.setVerticalGroup(
            panelProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProdLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Cantidad en almacen");

        diasRestLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        diasRestLabel.setForeground(new java.awt.Color(51, 51, 51));
        diasRestLabel.setText("Dias restantes:");

        jefeLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jefeLabel.setForeground(new java.awt.Color(51, 51, 51));
        jefeLabel.setText("Jefe:");

        gerenteLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        gerenteLabel.setForeground(new java.awt.Color(51, 51, 51));
        gerenteLabel.setText("Gerente:");

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        ctdBtns.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ctdBtns.setForeground(new java.awt.Color(51, 51, 51));
        ctdBtns.setText("Botones:");

        ctdBrazos.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ctdBrazos.setForeground(new java.awt.Color(51, 51, 51));
        ctdBrazos.setText("Brazos:");

        ctdPiernas.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ctdPiernas.setForeground(new java.awt.Color(51, 51, 51));
        ctdPiernas.setText("Piernas:");

        ctdCuerpos.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ctdCuerpos.setForeground(new java.awt.Color(51, 51, 51));
        ctdCuerpos.setText("Cuerpo:");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(ctdBtns)
                        .addGap(103, 272, Short.MAX_VALUE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ctdCuerpos)
                            .addComponent(ctdPiernas)
                            .addComponent(ctdBrazos))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(ctdBtns)
                .addGap(18, 18, 18)
                .addComponent(ctdBrazos)
                .addGap(18, 18, 18)
                .addComponent(ctdPiernas)
                .addGap(18, 18, 18)
                .addComponent(ctdCuerpos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        labelCtdEnsam.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        labelCtdEnsam.setForeground(new java.awt.Color(51, 51, 51));
        labelCtdEnsam.setText("Ensambladores:");

        aggEnsamblador.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        aggEnsamblador.setForeground(new java.awt.Color(51, 51, 51));
        aggEnsamblador.setText("+");
        aggEnsamblador.setBorderPainted(false);
        aggEnsamblador.setContentAreaFilled(false);
        aggEnsamblador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aggEnsamblador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggEnsambladorActionPerformed(evt);
            }
        });

        delEnsamblador.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        delEnsamblador.setForeground(new java.awt.Color(51, 51, 51));
        delEnsamblador.setText("-");
        delEnsamblador.setBorderPainted(false);
        delEnsamblador.setContentAreaFilled(false);
        delEnsamblador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delEnsamblador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delEnsambladorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(labelCtdEnsam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(aggEnsamblador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delEnsamblador)
                .addGap(22, 22, 22))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(labelCtdEnsam, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addComponent(aggEnsamblador)
                .addComponent(delEnsamblador))
        );

        labelCtdEnsam1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        labelCtdEnsam1.setForeground(new java.awt.Color(51, 51, 51));
        labelCtdEnsam1.setText("Panas disponibles:");

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));

        panasDisponLabel.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        panasDisponLabel.setForeground(new java.awt.Color(51, 51, 51));
        panasDisponLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panasDisponLabel.setText("0");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panasDisponLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panasDisponLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
        );

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));

        panasTotalesLabel.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        panasTotalesLabel.setForeground(new java.awt.Color(51, 51, 51));
        panasTotalesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panasTotalesLabel.setText("0");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panasTotalesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panasTotalesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        labelCtdEnsam2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        labelCtdEnsam2.setForeground(new java.awt.Color(51, 51, 51));
        labelCtdEnsam2.setText("Panas totales:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(188, 188, 188))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panelProd, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE))
                            .addComponent(diasRestLabel)
                            .addComponent(jefeLabel)
                            .addComponent(gerenteLabel))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(28, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelCtdEnsam1))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCtdEnsam2)
                                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(diasRestLabel)
                        .addGap(18, 18, 18)
                        .addComponent(jefeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(gerenteLabel)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCtdEnsam1)
                            .addComponent(labelCtdEnsam2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aggBotonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggBotonesActionPerformed
        agregarHilos(productoresBtn);
        System.out.println("Agregado productor boton");
    }//GEN-LAST:event_aggBotonesActionPerformed

    private void aggBrazosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggBrazosActionPerformed
        agregarHilos(productoresBrazos);
        System.out.println("Agregado productor brazos");
    }//GEN-LAST:event_aggBrazosActionPerformed

    private void aggPiernasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggPiernasActionPerformed
        agregarHilos(productoresPiernas);
        System.out.println("Agregado productor piernas");
    }//GEN-LAST:event_aggPiernasActionPerformed

    private void aggCuerpoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggCuerpoActionPerformed
        agregarHilos(productoresCuerpos);
        System.out.println("Agregado productor cuerpos");
    }//GEN-LAST:event_aggCuerpoActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void delBotonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBotonesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delBotonesActionPerformed

    private void delBrazosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBrazosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delBrazosActionPerformed

    private void delPiernasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delPiernasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delPiernasActionPerformed

    private void delCuerpoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delCuerpoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delCuerpoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void delEnsambladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delEnsambladorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delEnsambladorActionPerformed

    private void aggEnsambladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggEnsambladorActionPerformed
        agregarHilos(ensambladores);
        System.out.println("Agregado productor boton");
    }//GEN-LAST:event_aggEnsambladorActionPerformed

    private void aggBotonesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aggBotonesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_aggBotonesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }
    
    public void leerTxt() throws IOException {
        String path = "test\\datos.txt";
        String linea;
        String datosTxt = "";
        String[] listaDatos;
        File archivo = new File(path);
        
        //Se obtienen los datos del archivo txt para iniciar el programa.
        try {
            FileReader fr = new FileReader(archivo);
            BufferedReader br = new BufferedReader(fr);
            
            while((linea = br.readLine()) != null) {
                if(!linea.isEmpty()) {
                    datosTxt += linea + "\n";
                }
            }
            
            //Se asignan los valores adecuados a cada parametro.
            listaDatos = datosTxt.split(":");            
            this.tiempo = Integer.parseInt(listaDatos[1]);
            this.dias = Integer.parseInt(listaDatos[3]);
            this.maxBtn = Integer.parseInt(listaDatos[5]);
            this.maxBrazos = Integer.parseInt(listaDatos[7]);
            this.maxPiernas = Integer.parseInt(listaDatos[9]);
            this.maxCuerpos = Integer.parseInt(listaDatos[11]);
            this.inicioProdBtn = Integer.parseInt(listaDatos[13]);
            this.maxProdBtn = Integer.parseInt(listaDatos[15]);
            this.inicioProdBrazos = Integer.parseInt(listaDatos[17]);
            this.maxProdBrazos = Integer.parseInt(listaDatos[19]);
            this.inicioProdPiernas = Integer.parseInt(listaDatos[21]);
            this.maxProdPiernas = Integer.parseInt(listaDatos[23]);
            this.inicioProdCuerpos = Integer.parseInt(listaDatos[25]);
            this.maxProdCuerpos = Integer.parseInt(listaDatos[27]);
            this.inicioEnsambladores = Integer.parseInt(listaDatos[29]);
            this.maxEnsambladores = Integer.parseInt(listaDatos[31]);
            
            //Se inicializan los espacios donde estaran la máxima cantidad de productores
            this.productoresBtn = new Productor[maxProdBtn];
            this.productoresBrazos = new Productor[maxProdBrazos];
            this.productoresPiernas = new Productor[maxProdPiernas];
            this.productoresCuerpos = new Productor[maxProdCuerpos];
            this.ensambladores = new Ensamblador[maxEnsambladores];
            
            //Se asignan las cantidadades máximas de producción y se coloca la máxima cantidad de hilos por productor
            semProdBtn = new Semaphore(maxBtn);
            for (int i = 0; i < maxProdBtn; i++) {
                String nombre = "botones" + i;
                Productor prodBtn = new Productor(semEnsaBtn, semProdBtn, mutexBtn,contBotones ,nombre);
                productoresBtn[i] = prodBtn;
            }
            
            semProdBrazos = new Semaphore(maxBrazos);
            for (int i = 0; i < maxProdBrazos; i++) {
                String nombre = "brazos" + i;
                Productor prodBrazos = new Productor(semEnsaBrazos, semProdBrazos, mutexBrazos,contBrazos ,nombre);
                productoresBrazos[i] = prodBrazos;
            }
            
            semProdPiernas = new Semaphore(maxPiernas);
            for (int i = 0; i < maxProdPiernas; i++) {
                String nombre = "piernas" + i;
                Productor prodPiernas = new Productor(semEnsaPiernas, semProdPiernas, mutexPiernas,contPiernas ,nombre);
                productoresPiernas[i] = prodPiernas;
            }
            
            semProdCuerpos = new Semaphore(maxCuerpos);
            for (int i = 0; i < maxProdCuerpos; i++) {
                String nombre = "cuerpos" + i;
                Productor prodCuerpos = new Productor(semEnsaCuerpos, semProdCuerpos, mutexCuerpos,contCuerpos ,nombre);
                productoresCuerpos[i] = prodCuerpos;
            }
            
            for (int i = 0; i < maxEnsambladores; i++) {
                String nombre = "ensamblador" + i;
                Ensamblador ensamblador = new Ensamblador(semEnsaEns, semProdEns, mutexEns, nombre);
                ensamblador.botones = contBotones;
                ensamblador.brazos = contBrazos;
                ensamblador.piernas = contPiernas;
                ensamblador.cuerpos = contCuerpos;
                ensamblador.panas = contPanas;
                ensambladores[i] = ensamblador;
            }
            
            //Se inicializan los hilos.
            inicializarHilos(inicioProdBtn,productoresBtn);
            inicializarHilos(inicioProdBrazos,productoresBrazos);
            inicializarHilos(inicioProdPiernas,productoresPiernas);
            inicializarHilos(inicioProdCuerpos,productoresCuerpos);
            inicializarHilos(inicioEnsambladores,ensambladores);
        } catch(FileNotFoundException e) {
            System.out.println("Hubo un error en la lectura");
        }
    }
    
    /**
     *Se le indica al numero de hilos a correr.
     * @param inicioProd
     * Número minimo de hilos que deben comenzar en la producción.
     * @param tipo
     * El array de hilos de productores que se quiere comenzar.
     */
    public void inicializarHilos(int inicioProd, Productor[] tipo){
        for (int i = 0; i < inicioProd; i++) {
            tipo[i].start();
        }
    }
    
    public void inicializarHilos(int inicioProd, Ensamblador[] tipo){
        for (int i = 0; i < inicioProd; i++) {
            tipo[i].start();
        }
    }
    
    /**
     *Se indica iniciar o resumir al siguiente hilo disponible en el array.
     * @param inicioProd
     * Maximo numero de hilos.
     * @param tipo
     * El array de hilos donde se quieren inicializar.
     */
    public void agregarHilos(Productor[] tipo){
        for (int i = 0; i < tipo.length; i++) {
            if(!tipo[i].isAlive()){
                tipo[i].start();
                break;
            }
        }
    }
    
    public void agregarHilos(Ensamblador[] tipo){
        for (int i = 0; i < tipo.length; i++) {
            if(!tipo[i].isAlive()){
                tipo[i].start();
                break;
            }
        }
    }
      

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aggBotones;
    private javax.swing.JButton aggBrazos;
    private javax.swing.JButton aggCuerpo;
    private javax.swing.JButton aggEnsamblador;
    private javax.swing.JButton aggPiernas;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel ctdBrazos;
    private javax.swing.JLabel ctdBtns;
    private javax.swing.JLabel ctdCuerpos;
    private javax.swing.JLabel ctdPiernas;
    private javax.swing.JButton delBotones;
    private javax.swing.JButton delBrazos;
    private javax.swing.JButton delCuerpo;
    private javax.swing.JButton delEnsamblador;
    private javax.swing.JButton delPiernas;
    private javax.swing.JLabel diasRestLabel;
    private javax.swing.JLabel gerenteLabel;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel jefeLabel;
    private javax.swing.JLabel labelBrazosProd;
    private javax.swing.JLabel labelBrazosProd1;
    private javax.swing.JLabel labelCtdEnsam;
    private javax.swing.JLabel labelCtdEnsam1;
    private javax.swing.JLabel labelCtdEnsam2;
    private javax.swing.JLabel labelCuerpoProd;
    private javax.swing.JLabel labelCuerpoProd1;
    private javax.swing.JLabel labelPiernasProd;
    private javax.swing.JLabel labelPiernasProd1;
    private javax.swing.JLabel lableBtnProd;
    private javax.swing.JLabel lableBtnProd1;
    private javax.swing.JLabel panasDisponLabel;
    private javax.swing.JLabel panasTotalesLabel;
    private javax.swing.JPanel panelProd;
    private javax.swing.JPanel panelProd1;
    // End of variables declaration//GEN-END:variables

    

}
